version: '3'
services:
  app:
    build: .
    image: ${DOCKER_USER_ID}/flask
  production:
    image: ${DOCKER_USER_ID}/flask:${DEPLOY_NO}
    volumes:
      - .:/code
    command: python app.py
    ports:
      - "80:80"
